name: Build/Publish Docker Image 

on:
  push:
    branches:
      - 'docker-dev'
      - 'master'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag that the image will be built with'
        required: true
        default: 'latest'
      branch:
        description: 'branch that will be used to build image'
        required: true
        default: 'main'
  
jobs:
  build_velocity_manager:
    runs-on: ubuntu-18.04

    steps:
        
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push velocity-manager
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64, linux/amd64
        push: true
        tags: husarion/velocity-manager:noetic-latest
        cache-from: type=registry,ref=husarion/velocity-manager:noetic-latest
        cache-to: type=inline
